# Generated by Django 5.2.8 on 2025-11-19 07:12

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photos_name', models.CharField(max_length=100, verbose_name='图片名称')),
            ],
            options={
                'db_table': 'photos_category',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/', verbose_name='上传图片')),
                ('description', models.TextField(max_length=500, verbose_name='图片描述')),
                ('date_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建日期')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='photos.category', verbose_name='类别关联')),
            ],
            options={
                'db_table': 'photos_photo',
            },
        ),
    ]
