# Generated by Django 5.2.7 on 2025-11-20 12:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 20, 20, 4, 6, 278585), verbose_name='创建日期'),
        ),
    ]
